[package]
name = "pakreqWeb-rs"
version = "0.1.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
diesel = { version = "1.4", features= ["postgres", "chrono", "r2d2"] }
actix-web = "2.0"
yarte = { version = "0.7", features = ["with-actix-web"] }
r2d2 = "0.8"
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
env_logger = "0.7"
actix-rt = "1.0"
log = "0.4"
actix-identity = "0.2"
failure = "0.1"
argonautica = "0.2"
jsonwebtoken = "7"
