-- Generated by pgloader

CREATE TABLE public."user" (
	id bigserial NOT NULL,
	username text NULL,
	"admin" bool NULL,
	password_hash text NULL,
	CONSTRAINT idx_21560_sqlite_autoindex_user_1 PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_21560_sqlite_autoindex_user_2 ON public."user" USING btree (username);

CREATE TABLE public.oauth (
	uid int8 NOT NULL,
	"type" text NOT NULL,
	"oid" text NULL,
	"token" text NULL,
	CONSTRAINT idx_21552_sqlite_autoindex_oauth_1 PRIMARY KEY (uid, type),
	CONSTRAINT oauth_uid_fkey FOREIGN KEY (uid) REFERENCES "user"(id)
);

CREATE TABLE public.request (
	id bigserial NOT NULL,
	status text NULL,
	"type" text NULL,
	name text NULL,
	description text NULL,
	requester_id int8 NULL,
	packager_id int8 NULL,
	pub_date date NULL,
	note text NULL,
	CONSTRAINT idx_21545_sqlite_autoindex_request_1 PRIMARY KEY (id),
	CONSTRAINT request_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES "user"(id)
);
