#![allow(unused)]

use diesel::prelude::*;
use chrono::NaiveDate;

// Generated by diesel_ext

#[derive(Queryable, Debug)]
pub struct Oauth {
    pub uid: i64,
    pub type_: String,
    pub oid: Option<String>,
    pub token: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Request {
    pub id: i64,
    pub status: String,
    pub type_: String,
    pub name: String,
    pub description: Option<String>,
    pub requester_id: i64,
    pub packager_id: Option<i64>,
    pub pub_date: NaiveDate,
    pub note: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i64,
    pub username: String,
    pub admin: bool,
    pub password_hash: Option<String>,
}
